services:
  db:
    image: imresamu/postgis:17-3.5-bookworm
    container_name: peak-sight-django-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - peak-sight-django-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peak-sight-django-api
    env_file:
      - .env
    command: sh -c "uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:${API_PORT:-8000}"
    ports:
      - "127.0.0.1:${API_PORT:-8200}:${API_PORT:-8200}"
    volumes:
      - .:/app:cached
      - ../backend/datas:/datas:cached
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
    depends_on:
      db:
        condition: service_healthy

volumes:
  peak-sight-django-db-data:
