/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from ".././custom-fetch";

/**
 * @summary Root
 */
export type rootGetResponse200 = {
  data: unknown;
  status: 200;
};

export type rootGetResponseSuccess = rootGetResponse200 & {
  headers: Headers;
};

export type rootGetResponse = rootGetResponseSuccess;

export const getRootGetUrl = () => {
  return `/`;
};

export const rootGet = async (
  options?: RequestInit,
): Promise<rootGetResponse> => {
  return customFetch<rootGetResponse>(getRootGetUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * Database connection health check
 * @summary Health Check
 */
export type healthCheckHealthGetResponse200 = {
  data: unknown;
  status: 200;
};

export type healthCheckHealthGetResponseSuccess =
  healthCheckHealthGetResponse200 & {
    headers: Headers;
  };

export type healthCheckHealthGetResponse = healthCheckHealthGetResponseSuccess;

export const getHealthCheckHealthGetUrl = () => {
  return `/health`;
};

export const healthCheckHealthGet = async (
  options?: RequestInit,
): Promise<healthCheckHealthGetResponse> => {
  return customFetch<healthCheckHealthGetResponse>(
    getHealthCheckHealthGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Test database connection and return PostgreSQL version
 * @summary Test Db Connection
 */
export type testDbConnectionDbTestGetResponse200 = {
  data: unknown;
  status: 200;
};

export type testDbConnectionDbTestGetResponseSuccess =
  testDbConnectionDbTestGetResponse200 & {
    headers: Headers;
  };

export type testDbConnectionDbTestGetResponse =
  testDbConnectionDbTestGetResponseSuccess;

export const getTestDbConnectionDbTestGetUrl = () => {
  return `/db/test`;
};

export const testDbConnectionDbTestGet = async (
  options?: RequestInit,
): Promise<testDbConnectionDbTestGetResponse> => {
  return customFetch<testDbConnectionDbTestGetResponse>(
    getTestDbConnectionDbTestGetUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};
