/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

/**
 * BearSighting serializer
 */
export interface BearSighting {
  readonly id: number;
  /** @maxLength 100 */
  prefecture: string;
  /** @maxLength 100 */
  city: string;
  latitude: number;
  longitude: number;
  summary: string;
  /** @maxLength 200 */
  source_url: string;
  /**
   * @maxLength 200
   * @nullable
   */
  image_url?: string | null;
  reported_at: string;
}
