/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

export type BearListParams = {
  /**
   * 市区町村でフィルタ
   */
  city?: string;
  /**
   * 取得する最大件数
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  /**
   * 都道府県でフィルタ
   */
  prefecture?: string;
};
