/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

export type ListPathsPathsGetParams = {
  skip?: number;
  limit?: number;
  highway?: string | null;
  minlat?: number | null;
  minlon?: number | null;
  maxlat?: number | null;
  maxlon?: number | null;
};
