/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

import type { MountainArea } from "./mountainArea";
import type { MountainDetail } from "./mountainDetail";
import type { MountainElevation } from "./mountainElevation";
import type { MountainLat } from "./mountainLat";
import type { MountainLon } from "./mountainLon";
import type { MountainNameEn } from "./mountainNameEn";
import type { MountainOtherNames } from "./mountainOtherNames";
import type { MountainPageUrl } from "./mountainPageUrl";
import type { MountainPhotoUrl } from "./mountainPhotoUrl";
import type { MountainYamatan } from "./mountainYamatan";
import type { MountainYomi } from "./mountainYomi";
import type { Prefecture } from "./prefecture";
import type { Type } from "./type";

/**
 * MountainのAPI応答スキーマ
 */
export interface Mountain {
  ptid: string;
  name: string;
  yomi?: MountainYomi;
  other_names?: MountainOtherNames;
  yamatan?: MountainYamatan;
  name_en?: MountainNameEn;
  elevation?: MountainElevation;
  lat?: MountainLat;
  lon?: MountainLon;
  detail?: MountainDetail;
  area?: MountainArea;
  photo_url?: MountainPhotoUrl;
  page_url?: MountainPageUrl;
  id: number;
  types?: Type[];
  prefectures?: Prefecture[];
  created_at: string;
  updated_at: string;
}
