/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */
import type { Prefecture } from "./prefecture";
import type { Type } from "./type";

/**
 * Mountain serializer
 */
export interface Mountain {
  readonly id: number;
  /** @maxLength 255 */
  ptid: string;
  /** @maxLength 255 */
  name: string;
  /**
   * @maxLength 255
   * @nullable
   */
  yomi?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  other_names?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  yamatan?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  name_en?: string | null;
  /** @nullable */
  elevation?: number | null;
  /** @nullable */
  lat?: number | null;
  /** @nullable */
  lon?: number | null;
  /** @nullable */
  detail?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  area?: string | null;
  /**
   * @maxLength 512
   * @nullable
   */
  photo_url?: string | null;
  /**
   * @maxLength 512
   * @nullable
   */
  page_url?: string | null;
  readonly types: readonly Type[];
  readonly prefectures: readonly Prefecture[];
  readonly created_at: string;
  readonly updated_at: string;
}
