/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

import type { MountainUpdateArea } from "./mountainUpdateArea";
import type { MountainUpdateDetail } from "./mountainUpdateDetail";
import type { MountainUpdateElevation } from "./mountainUpdateElevation";
import type { MountainUpdateLat } from "./mountainUpdateLat";
import type { MountainUpdateLon } from "./mountainUpdateLon";
import type { MountainUpdateName } from "./mountainUpdateName";
import type { MountainUpdateNameEn } from "./mountainUpdateNameEn";
import type { MountainUpdateOtherNames } from "./mountainUpdateOtherNames";
import type { MountainUpdatePageUrl } from "./mountainUpdatePageUrl";
import type { MountainUpdatePhotoUrl } from "./mountainUpdatePhotoUrl";
import type { MountainUpdatePrefs } from "./mountainUpdatePrefs";
import type { MountainUpdateTypes } from "./mountainUpdateTypes";
import type { MountainUpdateYamatan } from "./mountainUpdateYamatan";
import type { MountainUpdateYomi } from "./mountainUpdateYomi";

/**
 * Mountain更新時のスキーマ（すべてオプショナル）
 */
export interface MountainUpdate {
  name?: MountainUpdateName;
  yomi?: MountainUpdateYomi;
  other_names?: MountainUpdateOtherNames;
  yamatan?: MountainUpdateYamatan;
  name_en?: MountainUpdateNameEn;
  elevation?: MountainUpdateElevation;
  lat?: MountainUpdateLat;
  lon?: MountainUpdateLon;
  detail?: MountainUpdateDetail;
  area?: MountainUpdateArea;
  photo_url?: MountainUpdatePhotoUrl;
  page_url?: MountainUpdatePageUrl;
  types?: MountainUpdateTypes;
  prefs?: MountainUpdatePrefs;
}
