/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */
import type { Mountain } from "./mountain";

/**
 * Mountain一覧応答スキーマ
 */
export interface MountainList {
  total: number;
  skip: number;
  limit: number;
  items: Mountain[];
}
