/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */
import type { MountainTypeDetailDetail } from "./mountainTypeDetailDetail";

/**
 * Mountain-Type関係の詳細情報（中間テーブルのdetailフィールド用）
 */
export interface MountainTypeDetail {
  type_id: string;
  name: string;
  detail?: MountainTypeDetailDetail;
}
