/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Mountain-Type関係の詳細情報（中間テーブルのdetailフィールド用）
 */
export interface MountainTypeDetail {
  type_id: string;
  name: string;
  /** @nullable */
  detail?: string | null;
}
