/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

export type PathsBulkDeleteCreateParams = {
  /**
   * 検索範囲の最大緯度（bboxフィルタ用）
   */
  maxlat: number;
  /**
   * 検索範囲の最大経度（bboxフィルタ用）
   */
  maxlon: number;
  /**
   * 検索範囲の最小緯度（bboxフィルタ用）
   */
  minlat: number;
  /**
   * 検索範囲の最小経度（bboxフィルタ用）
   */
  minlon: number;
};
