/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */
import type { Point } from "./point";

export type PathDetailPathGraphic = Point[] | null;
