/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

export type PathTagsItem = {
  readonly id?: number;
  /**
   * @maxLength 255
   * @nullable
   */
  highway?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  source?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  difficulty?: number | null;
  /**
   * @maxLength 255
   * @nullable
   */
  kuma?: string | null;
  readonly created_at?: string;
};
