/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

import type { PathCreatedAt } from "./pathCreatedAt";
import type { PathGeometry } from "./pathGeometry";
import type { PathId } from "./pathId";
import type { PathMaxlat } from "./pathMaxlat";
import type { PathMaxlon } from "./pathMaxlon";
import type { PathMinlat } from "./pathMinlat";
import type { PathMinlon } from "./pathMinlon";
import type { PathTag } from "./pathTag";
import type { PathUpdatedAt } from "./pathUpdatedAt";

/**
 * Path API応答スキーマ（関連データ含む）
 */
export interface Path {
  osm_id: number;
  type: string;
  minlat?: PathMinlat;
  minlon?: PathMinlon;
  maxlat?: PathMaxlat;
  maxlon?: PathMaxlon;
  id?: PathId;
  geometries?: PathGeometry[];
  tags?: PathTag[];
  created_at?: PathCreatedAt;
  updated_at?: PathUpdatedAt;
}
