/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */
import type { PathGeometriesItem } from "./pathGeometriesItem";
import type { PathTagsItem } from "./pathTagsItem";

export interface Path {
  readonly id?: number;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  osm_id: number;
  /** @maxLength 255 */
  type: string;
  /** @nullable */
  minlat?: number | null;
  /** @nullable */
  minlon?: number | null;
  /** @nullable */
  maxlat?: number | null;
  /** @nullable */
  maxlon?: number | null;
  readonly geometries?: readonly PathGeometriesItem[];
  readonly tags?: readonly PathTagsItem[];
  readonly created_at?: string;
  readonly updated_at?: string;
}
