/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

import type { PathDetailDifficulty } from "./pathDetailDifficulty";
import type { PathDetailId } from "./pathDetailId";
import type { PathDetailPathGraphic } from "./pathDetailPathGraphic";
import type { PathDetailPathId } from "./pathDetailPathId";

/**
 * Pathの詳細情報スキーマ
 */
export interface PathDetail {
  id?: PathDetailId;
  path_id?: PathDetailPathId;
  osm_id: number;
  type: string;
  difficulty?: PathDetailDifficulty;
  path_graphic?: PathDetailPathGraphic;
}
