/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

import type { PathTagCreatedAt } from "./pathTagCreatedAt";
import type { PathTagDifficulty } from "./pathTagDifficulty";
import type { PathTagHighway } from "./pathTagHighway";
import type { PathTagId } from "./pathTagId";
import type { PathTagKuma } from "./pathTagKuma";
import type { PathTagPathId } from "./pathTagPathId";
import type { PathTagSource } from "./pathTagSource";

/**
 * PathTag API応答スキーマ
 */
export interface PathTag {
  highway?: PathTagHighway;
  source?: PathTagSource;
  difficulty?: PathTagDifficulty;
  kuma?: PathTagKuma;
  id?: PathTagId;
  path_id?: PathTagPathId;
  created_at?: PathTagCreatedAt;
}
