/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

/**
 * PathGeometry serializer
 */
export interface PathGeometry {
  readonly id: number;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  node_id: number;
  lat: number;
  lon: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  sequence: number;
}
