/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */
import type { Point } from "./point";
import type { PathGeometryWithSequence } from "./pathGeometryWithSequence";

/**
 * Pathの詳細情報Serializer
 */
export interface PathDetail {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  path_id?: number | null;
  osm_id: number;
  type: string;
  /** @nullable */
  difficulty?: number | null;
  /** @nullable */
  path_graphic?: Point[] | null;
  /** @nullable */
  geometries?: PathGeometryWithSequence[] | null;
}
