/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

/**
 * PathGeometry with sequence from through model
 */
export interface PathGeometryWithSequence {
  readonly id: number;
  readonly node_id: number;
  readonly lat: number;
  readonly lon: number;
  readonly sequence: number;
}
