/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

/**
 * 座標点のSerializer
 */
export interface Point {
  x: number;
  y: number;
  lon: number;
  lat: number;
}
