/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 座標点のスキーマ
 */
export interface Point {
  x: number;
  y: number;
  lon: number;
  lat: number;
}
