/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

/**
 * Prefecture serializer
 */
export interface Prefecture {
  readonly id: number;
  /** @maxLength 255 */
  pref_id: string;
  /** @maxLength 255 */
  name: string;
  readonly created_at: string;
}
