# Generated by Django 5.2.7 on 2025-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BearSighting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefecture', models.CharField(max_length=100, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('summary', models.TextField(verbose_name='概要')),
                ('source_url', models.URLField(verbose_name='情報源URL')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('reported_at', models.DateTimeField(verbose_name='報告日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'クマ目撃情報',
                'verbose_name_plural': 'クマ目撃情報',
                'db_table': 'bear_sighting',
                'ordering': ['-reported_at'],
            },
        ),
    ]
