/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */
import type { MountainCreateYomi } from './mountainCreateYomi';
import type { MountainCreateOtherNames } from './mountainCreateOtherNames';
import type { MountainCreateYamatan } from './mountainCreateYamatan';
import type { MountainCreateNameEn } from './mountainCreateNameEn';
import type { MountainCreateElevation } from './mountainCreateElevation';
import type { MountainCreateLat } from './mountainCreateLat';
import type { MountainCreateLon } from './mountainCreateLon';
import type { MountainCreateDetail } from './mountainCreateDetail';
import type { MountainCreateArea } from './mountainCreateArea';
import type { MountainCreatePhotoUrl } from './mountainCreatePhotoUrl';
import type { MountainCreatePageUrl } from './mountainCreatePageUrl';
import type { MountainTypeDetail } from './mountainTypeDetail';
import type { PrefectureBase } from './prefectureBase';

/**
 * Mountain作成時のスキーマ
 */
export interface MountainCreate {
  ptid: string;
  name: string;
  yomi?: MountainCreateYomi;
  other_names?: MountainCreateOtherNames;
  yamatan?: MountainCreateYamatan;
  name_en?: MountainCreateNameEn;
  elevation?: MountainCreateElevation;
  lat?: MountainCreateLat;
  lon?: MountainCreateLon;
  detail?: MountainCreateDetail;
  area?: MountainCreateArea;
  photo_url?: MountainCreatePhotoUrl;
  page_url?: MountainCreatePageUrl;
  types?: MountainTypeDetail[];
  prefs?: PrefectureBase[];
}
