/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

/**
 * PathGeometry API応答スキーマ
 */
export interface PathGeometry {
  lat: number;
  lon: number;
  sequence: number;
  id: number;
  node_id: number;
}
