/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

/**
 * 共通のPrefectureフィールド
 */
export interface PrefectureBase {
  pref_id: string;
  name: string;
}
