/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * OpenAPI spec version: 0.1.0
 */

/**
 * PrefectureのAPI応答スキーマ
 */
export interface Prefecture {
  pref_id: string;
  name: string;
  id: number;
  created_at: string;
}
