# Generated by Django 5.2.7 on 2025-10-27 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(db_index=True, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('minlat', models.FloatField(blank=True, null=True)),
                ('minlon', models.FloatField(blank=True, null=True)),
                ('maxlat', models.FloatField(blank=True, null=True)),
                ('maxlon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paths',
            },
        ),
        migrations.CreateModel(
            name='PathGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sequence', models.IntegerField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='paths.path')),
            ],
            options={
                'db_table': 'path_geometries',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PathTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highway', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('kuma', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='paths.path')),
            ],
            options={
                'db_table': 'path_tags',
            },
        ),
    ]
