# Generated by Django 5.2.7 on 2025-10-27 05:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='path',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='path',
            index=models.Index(fields=['minlat', 'minlon', 'maxlat', 'maxlon'], name='paths_minlat_5ac13f_idx'),
        ),
    ]
