# Generated by Django 5.2.7 on 2025-11-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_path_bbox_path_route_path_paths_minlat_5ac13f_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathgeometry',
            name='path',
        ),
        migrations.AddField(
            model_name='pathgeometry',
            name='path',
            field=models.ManyToManyField(related_name='geometries', to='paths.path'),
        ),
    ]
