# Generated by Django 5.2.7 on 2025-11-08 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_remove_pathgeometry_path_pathgeometry_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathgeometry',
            options={},
        ),
        migrations.RemoveField(
            model_name='pathgeometry',
            name='path',
        ),
        migrations.RemoveField(
            model_name='pathgeometry',
            name='sequence',
        ),
        migrations.CreateModel(
            name='PathGeometryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_orders', to='paths.pathgeometry')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry_orders', to='paths.path')),
            ],
            options={
                'db_table': 'path_geometry_order',
                'ordering': ['sequence'],
                'unique_together': {('path', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='path',
            name='geometries',
            field=models.ManyToManyField(blank=True, related_name='paths', through='paths.PathGeometryOrder', to='paths.pathgeometry'),
        ),
    ]
