# Generated by Django 5.2.7 on 2025-10-27 05:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='mountain',
            index=models.Index(fields=['lat', 'lon'], name='mountains_lat_89112d_idx'),
        ),
    ]
