/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

import { customFetch } from ".././custom-fetch";
import type { PaginatedPathList, Path, RouteListParams } from ".././models";

/**
 * ダイクストラ法でstartノードからdestノードまでの最短経路のPath一覧を取得
 */
export type routeListResponse200 = {
  data: PaginatedPathList;
  status: 200;
};

export type routeListResponseSuccess = routeListResponse200 & {
  headers: Headers;
};

export type routeListResponse = routeListResponseSuccess;

export const getRouteListUrl = (params: RouteListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/route/?${stringifiedParams}`
    : `/route/`;
};

export const routeList = async (
  params: RouteListParams,
  options?: RequestInit,
): Promise<routeListResponse> => {
  return customFetch<routeListResponse>(getRouteListUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * PathGeometry API ViewSet (Read-only) - Dijkstra shortest path
 */
export type routeRetrieveResponse200 = {
  data: Path;
  status: 200;
};

export type routeRetrieveResponseSuccess = routeRetrieveResponse200 & {
  headers: Headers;
};

export type routeRetrieveResponse = routeRetrieveResponseSuccess;

export const getRouteRetrieveUrl = (id: number) => {
  return `/route/${id}/`;
};

export const routeRetrieve = async (
  id: number,
  options?: RequestInit,
): Promise<routeRetrieveResponse> => {
  return customFetch<routeRetrieveResponse>(getRouteRetrieveUrl(id), {
    ...options,
    method: "GET",
  });
};
