/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

import { customFetch } from ".././custom-fetch";
import type { BearListParams, PaginatedBearSightingList } from ".././models";

/**
 * BearSighting一覧を取得
 */
export type bearListResponse200 = {
  data: PaginatedBearSightingList;
  status: 200;
};

export type bearListResponseSuccess = bearListResponse200 & {
  headers: Headers;
};

export type bearListResponse = bearListResponseSuccess;

export const getBearListUrl = (params?: BearListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/bear/?${stringifiedParams}`
    : `/bear/`;
};

export const bearList = async (
  params?: BearListParams,
  options?: RequestInit,
): Promise<bearListResponse> => {
  return customFetch<bearListResponse>(getBearListUrl(params), {
    ...options,
    method: "GET",
  });
};
