/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Collect Map API
 * Django backend for Collect Map API - Mountain and Path data management
 * OpenAPI spec version: 1.0.0
 */

import { customFetch } from ".././custom-fetch";
import type {
  PaginatedPathList,
  Path,
  PathDetail,
  PathsListParams,
  PathsRouteListParams,
} from ".././models";

/**
 * 指定されたIDのPathの詳細情報を取得
 */
export type pathsListResponse200 = {
  data: PaginatedPathList;
  status: 200;
};

export type pathsListResponseSuccess = pathsListResponse200 & {
  headers: Headers;
};

export type pathsListResponse = pathsListResponseSuccess;

export const getPathsListUrl = (params?: PathsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/paths/?${stringifiedParams}`
    : `/paths/`;
};

export const pathsList = async (
  params?: PathsListParams,
  options?: RequestInit,
): Promise<pathsListResponse> => {
  return customFetch<pathsListResponse>(getPathsListUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * 指定されたIDのPathの詳細情報を取得（標高グラフデータ付き）
 */
export type pathsRetrieveResponse200 = {
  data: PathDetail;
  status: 200;
};

export type pathsRetrieveResponseSuccess = pathsRetrieveResponse200 & {
  headers: Headers;
};

export type pathsRetrieveResponse = pathsRetrieveResponseSuccess;

export const getPathsRetrieveUrl = (id: number) => {
  return `/paths/${id}/`;
};

export const pathsRetrieve = async (
  id: number,
  options?: RequestInit,
): Promise<pathsRetrieveResponse> => {
  return customFetch<pathsRetrieveResponse>(getPathsRetrieveUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * ダイクストラ法でstartノードからdestノードまでの最短経路のPath一覧を取得
 */
export type pathsRouteListResponse200 = {
  data: PaginatedPathList;
  status: 200;
};

export type pathsRouteListResponseSuccess = pathsRouteListResponse200 & {
  headers: Headers;
};

export type pathsRouteListResponse = pathsRouteListResponseSuccess;

export const getPathsRouteListUrl = (params: PathsRouteListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/paths/route/?${stringifiedParams}`
    : `/paths/route/`;
};

export const pathsRouteList = async (
  params: PathsRouteListParams,
  options?: RequestInit,
): Promise<pathsRouteListResponse> => {
  return customFetch<pathsRouteListResponse>(getPathsRouteListUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * PathGeometry API ViewSet (Read-only) - Dijkstra shortest path
 */
export type pathsRouteRetrieveResponse200 = {
  data: Path;
  status: 200;
};

export type pathsRouteRetrieveResponseSuccess =
  pathsRouteRetrieveResponse200 & {
    headers: Headers;
  };

export type pathsRouteRetrieveResponse = pathsRouteRetrieveResponseSuccess;

export const getPathsRouteRetrieveUrl = (id: number) => {
  return `/paths/route/${id}/`;
};

export const pathsRouteRetrieve = async (
  id: number,
  options?: RequestInit,
): Promise<pathsRouteRetrieveResponse> => {
  return customFetch<pathsRouteRetrieveResponse>(getPathsRouteRetrieveUrl(id), {
    ...options,
    method: "GET",
  });
};
