name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise install

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./frontend
        
      - name: Run Format & Lint Check with Biome
        run: pnpm biome ci src/
        working-directory: ./frontend

      - name: Run Type Check
        run: pnpm type-check
        working-directory: ./frontend
