name: Deploy

on:
  push:
    branches:
      - main

env:
  MAPTILER_KEY: ${{ secrets.MAPTILER_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup pnpm
        uses: pnpm/action-setup@master
        with:
          version: 10.18.0

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 22.16.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_TARGET }}
            git pull origin main
            cd frontend
            ~/.local/bin/mise install
            pnpm install --frozen-lockfile
            pnpm build
            ~/.volta/bin/pm2 restart pm2.config.cjs --update-env
